# Generated by Django 5.2.8 on 2025-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='time_to_generate',
            field=models.FloatField(blank=True, help_text='Time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='time_to_summarize',
            field=models.FloatField(blank=True, help_text='Time in seconds', null=True),
        ),
    ]
