# Generated by Django 5.2.8 on 2025-11-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_blogpost_model_used_blogpost_time_to_generate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='article_size',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=15, null=True),
            preserve_default=False,
        ),
    ]
