# Generated by Django 5.2.8 on 2025-11-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0005_alter_blogpost_article_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article_size',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=15, null=True),
        ),
    ]
