# Generated by Django 5.2.8 on 2025-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0006_alter_blogpost_article_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
